---
  dataset: pascal_context_59
  annotation_dir: /home/user/data/datasets/Datasets_HSN/VOC2010/PASCAL-Context/trainval
  labels_file: /home/user/data/datasets/Datasets_HSN/VOC2010/PASCAL-Context/labels.txt
  img_dir: /home/user/data/datasets/Datasets_HSN/VOC2010/JPEGImages
  used_classes: /home/user/<path/to/quash>/config/pc59.json