defaults:
  - data_paths: default
  - map_config: vlmaps
  - params: default
  - _self_
nav:
  valid_range: 1
  vis: False
  tasks_per_scene: 20
scene_id: 0
output: "${data_paths.home}/code/vlmaps/data/mapdata"

# indexing params
decay_rate: 0.01
index_2d: True
init_categories: True
regions: True
voxel_map: True
# REGULAR = 0,
# POSTPROCESSED = 1,
# INSTANCES = 2,
# PREDICTED = 3,
# VLMAP_INSTANCES = 4,
# OUR_INSTANCES = 5,
# PREDICTED_POSTPROCESSED = 6,
ask_for_type: False
type: 0
ask_for_color: True
# 0: rgb
# 1: semantic
# 2: regions
# 3: instances
color: 1
filter: False
ask_for_filter: False
filter_label: 27
classes: "${data_paths.home}/code/vlmaps/cfg/mpcat40_edit.tsv"
delimiter: ;
direct_path: True
direct_path_path: "/home/user/hdd/datasets/vlmaps_dataset/5LpN3gDmAk7_1/vlmap/vlmaps-lseg-0.05-median.h5df"
# direct_path_path: "/home/user/hdd/datasets/vlmaps_dataset/5LpN3gDmAk7_1/vlmap/vlmaps-lseg-0.05-rt.h5df"
# direct_path_path: "/home/user/hdd/datasets/vlmaps_dataset/5LpN3gDmAk7_1/vlmap/vlmaps-lseg-0.05.h5df"
# direct_path_path: "/home/user/hdd/datasets/vlmaps_dataset/5LpN3gDmAk7_1/vlmap/vlmaps-lseg-0.05-nort.h5df"
# direct_path_path: "/home/user/hdd/datasets/vlmaps_dataset/5LpN3gDmAk7_1/vlmap/vlmaps-lseg-0.2-rt.h5df"


# direct_path_path: "/home/user/data/dbg-maps/vlmaps-lseg-0.05.h5df"
direct_path_path: "/home/user/data/dbg-maps/vlmaps-lseg-0.05-sample.h5df"
# direct_path_path: "/home/user/data/dbg-maps/vlmaps-lseg-0.05-median.h5df"
# direct_path_path: "/home/user/data/dbg-maps/transformer-lora-lseg.h5df"
# direct_path_path: "/home/user/data/dbg-maps/vlmaps-openseg-0.05.h5df"
# direct_path_path: "/home/user/data/dbg-maps/vlmaps-openseg-0.05-sample.h5df"
# direct_path_path: "/home/user/data/dbg-maps/vlmaps-openseg-0.05-median.h5df"
# direct_path_path: "/home/user/data/dbg-maps/transformer-lora-openseg.h5df"


# FLAT
#################
# run 1
#################
#direct_path_path: "/home/user/hdd/datasets/vlmaps_dataset_flat/vlmaps_dataset/run1/vlmap/vlmaps-lseg-0.1.h5df"
# direct_path_path: "/home/user/hdd/datasets/vlmaps_dataset_flat/vlmaps_dataset/run1/vlmap/vlmaps-lseg-0.05.h5df"
# run 1
#################
#direct_path_path: "/home/user/hdd/datasets/vlmaps_dataset_flat/vlmaps_dataset/run2/vlmap/vlmaps-lseg-0.1.h5df"
# direct_path_path: "/home/user/hdd/datasets/vlmaps_dataset_flat/vlmaps_dataset/run2/vlmap/vlmaps-lseg-0.05.h5df"


# direct_path_path: "/mnt/hdd/2-vlmaps-maps/vlmap/vlmaps-lseg.h5df"
# direct_path_path: "/mnt/hdd/2-vlmaps-maps/vlmap/vlmaps-lseg-0.1.h5df"
# direct_path_path: "/mnt/hdd/2-vlmaps-maps/vlmap/vlmaps-lseg-0.2.h5df"
# direct_path_path: "/mnt/hdd/2-vlmaps-maps/vlmap/vlmaps-openseg.h5df"
# direct_path_path: "/mnt/hdd/2-vlmaps-maps/vlmap/vlmaps-openseg-0.1.h5df"
# direct_path_path: "/mnt/hdd/2-vlmaps-maps/vlmap/vlmaps-openseg-0.2.h5df"
